### PR TITLE
feat: add 'all' option to add all the documentation to the readme in one go

### PR DESCRIPTION
**Pull request by larmitage-bjss**
To merge after #523 

I think this functionality is especially useful with the new ability to document workflows as you may (like me) have a readme in your `.github/workflows` directory where you want to document a number of workflows, and this makes it easier having one comment per workflow to insert all the docs at once

### CODE REVIEW

**Comment by npalm** [comment]
Megalinter error can be ingored. I have to update the config. It seems not respecting all ignore files.

**Comment by npalm** [comment]
This PR seems on top of another or not? TIle mention only docs are changed.

**Comment by larmitage-bjss** [comment]
@npalm yes, it depends on #523 being merged first

**Comment by npalm** [comment]
@larmitage-bjss this PR requires after mering the workflow one a rebase.

**Comment by larmitage-bjss** [comment]
@npalm this is ready for review please

**Review by npalm — APPROVED** [review]
@larmitage-bjss thx looks all good. Great contribution again 🚀

**Pull request merged**
